name: Latest Blog Posts from Hashnode

on:
  workflow_dispatch:
  schedule:
    - cron: "15 18 * * *"

jobs:
  fetch-blog-posts:
    name: Update amitkbiswas01 profile readme with latest blog posts from hashnode
    runs-on: ubuntu-latest
    steps:
      - name: "📥  Fetching Repository Contents"
        uses: actions/checkout@main
      - name: "📚  Hashnode Updater"
        uses: "varunsridharan/action-hashnode-blog@main"
        with:
          USERNAME: "amitkbiswas"
          STYLE: "blog-grid"
          COUNT: 4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
